### ISSUE TITLE
[BUG]: Snake Animation

### ISSUE THREAD

**Issue by sun0225SUN** [JayantGoel001/JayantGoel001#10]
### Description of the bug

Hello, there seems to be a bug in that snake animation. I think you should update it.
![image](https://user-images.githubusercontent.com/79169717/211556630-19c73493-6768-40c5-a591-a1d11dc7ab47.png)
here is the original author's repo https://github.com/Platane/Platane
you know what to do next, haha, wish you a happy life！

### Steps To Reproduce

none

### Additional Information

none

**Comment by JayantGoel001** [comment]
Hello @sun0225SUN 👋,
Thanks a lot for reporting that bug🐛.
It now has been fixed.😁🎉
