### ISSUE TITLE
about waifu model

### ISSUE THREAD

**Issue by Asura0209** [JayantGoel001/JayantGoel001#13]
### Description of the bug

Hi, @JayantGoel001 
How are you?
I have some question
Can you help me?

### Steps To Reproduce

about waifu models

**Comment by JayantGoel001** [comment]
Hi @Asura0209,
I am Great 
How about you?
Yes, how can I help?

**Comment by Asura0209** [comment]
yes, 
Thanks for your reply

**Comment by Asura0209** [comment]
Is it possible to implement your waifu model(in your portfolio) in react app?

**Comment by JayantGoel001** [comment]
> Is it possible to implement your waifu model(in your portfolio) in react app?

Yes, you can implement the waifu model anywhere using the `waifu.min.js` file.

**Comment by Asura0209** [comment]
thanks everything. @JayantGoel001 
you are awesome.
